context:
  version: "1.0.0"

package:
  name: q-kx-stringutils
  version: ${{ version }}

source:
  url: https://github.com/EwanC1234567/qStringUtils/archive/refs/heads/main.tar.gz
  sha256: d6a96f0cf6fb14b62b88f57cf5add869377a668cdb0bbcacef36fb7a7a83fb0f
  filter:
    exclude:
      - recipe/**

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/lib/q/mod/kx
    - cp stringutils.q $PREFIX/lib/q/mod/kx/

requirements:
  run: []

tests:
  - script:
    - test -f ${PREFIX}/lib/q/mod/kx/stringutils.q
